import { SSKey } from '~/types/spritesheets'
import { ObjectKey, InitObject } from '~/types/interphaser'
import { CommandID } from '~/types/stack'

export const COMMON_SPRITES = [
	'-',
	'0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21',
	'backbutton',
	'close',
	'execute',
	'execute-hover',
	'nextlevel',
	'ok',
	'ok-hover',
	'open',
	'ossie',
	'playagain',
	'reset',
	'slash',
	'step',
	'step-crnt',
	'stop',
	'stop-hover',
]
export const COMMON_MODALS: SSKey[] = [
	SSKey.fail,
	SSKey.levelcomplete,
]

export const BRACKET_OBJECTS: CommandID[] = [ 'if', 'else', 'for' ]
export const COMMON_OBJECTS: Array<ObjectKey | string> = [
	'backButton',
	'close',
	'execute',
	'fail',
	'levelcount_slash',
	'levelcount_total_pt1',
	'levelcount_total_pt2',
	'ok',
	'open',
	'player',
	'reset',
	'stepcount',
	'stepcount_slash',
	'levelcomplete',
]

export const INIT_OBJECTS: InitObject[] = [
	'backButton',
	'close',
	'else',
	'execute',
	'for',
	'for_till',
	'for_x',
	'if_padlinks',
	'if_padrechts',
	'if_padvooruit',
	'open',
	'player',
	'reset',
	'questionmark',
	'step',
	'steppixles',
	'steppixles_back',
	'stepcount',
	'stepcount_slash',
	'turndegrees',
	'turnleft',
	'turnright',
]
export const OBJECTS_MULTIPLE: ObjectKey[] = [
	'close',
	'else',
	'for',
	'for_till',
	'for_x',
	'if_padlinks',
	'if_padrechts',
	'if_padvooruit',
	'open',
	'step',
	'steppixles',
	'steppixles_back',
	'turndegrees',
	'turnleft',
	'turnright',
]
export const NUMBER_COMMANDS: ObjectKey[] = [
	'for_x',
	'steppixles',
	'steppixles_back',
	'skippixles',
	'turndegrees',
]
export const LEVELS = [
	'level1',
	'level2',
	'level3a',
	'level3b',
	'level3c',
	'level4',
	'level5',
	'level6',
	'level7',
	'level8',
	'level9',
	'level10',
	'level11',
	'level12',
	'level13',
	'level14',
	'level15',
	'level16',
]
