export const COMMON_SPRITES = [
	'-',
	'0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21',
	'backbutton',
	'close',
	'execute',
	'execute-hover',
	'nextlevel',
	'ok',
	'ok-hover',
	'open',
	'ossie',
	'playagain',
	'reset',
	'slash',
	'step',
	'step-crnt',
]
export const COMMON_MODALS = [
	'fail',
	'levelcomplete',
]

export const BRACKET_OBJECTS = [ 'if', 'else', 'for' ]
export const COMMON_OBJECTS = [
	'backButton',
	'close',
	'execute',
	'fail',
	'levelcount_slash',
	'levelcount_total_pt1',
	'levelcount_total_pt2',
	'ok',
	'open',
	'player',
	'reset',
	'stepcount',
	'stepcount_slash',
	'levelcomplete',
]
export const INIT_OBJECTS = [
	'backButton',
	'close',
	'else',
	'execute',
	'for',
	'for_till',
	'for_x',
	'if_padlinks',
	'if_padrechts',
	'if_padvooruit',
	'open',
	'player',
	'reset',
	'questionmark',
	'step',
	'steppixles',
	'stepcount',
	'stepcount_slash',
	'turndegrees',
	'turnleft',
	'turnright',
]
export const OBJECTS_MULTIPLE = [
	'close',
	'else',
	'for',
	'for_till',
	'for_x',
	'if_padlinks',
	'if_padrechts',
	'if_padvooruit',
	'open',
	'turndegrees',
	'turnleft',
	'turnright',
	'step',
	'steppixles',
]
export const NUMBER_COMMANDS = [
	'for_x',
	'steppixles',
	'turndegrees',
]
export const LEVELS = [
	'level1',
	'level2',
	'level3a',
	'level3b',
	'level3c',
	'level4',
	'level5',
	'level6',
	'level7',
	'level8',
	'level9',
	'level10',
	'level11',
	'level12',
	'level13',
	'level14a',
	'level14b',
	'level15',
	'level16',
]
